name: AWS

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download ngrok

      run: |

        Invoke-WebRequest https://s02vlx.storage.yandex.net/rdisk/cf489cce6a013e7b3cb82f444adf17a5e5c30807dedfa8da4e27155e38da2338/645d638d/V1eGyeIuL0mVrohNXWPG6KahQx-6cERKfbYbFSekEynfonNH3OpCN9aX9msyrCkG60WiyN9cXsHufZtL0tt7Ow==?uid=0&filename=ngrok.zip&disposition=attachment&hash=LiQYnfoETS/XYqP8/TLruSYrETGF5Nx46W8jqF2j%2BgDg8EhfT4svFT8%2BbOIPhj1bq/J6bpmRyOJonT3VoXnDag%3D%3D%3A/ngrok.zip&limit=0&content_type=application%2Fzip&owner_uid=1479552452&fsize=14001275&hid=504cfdbed63e6a832e9d00efcf5f0db5&media_type=compressed&tknv=v2&rtoken=S0Oq3CsVCkWx&force_default=no&ycrid=na-6c0ba54ed606133bb2045ffe84b3bc00-downloader2h&ts=5fb7200463d40&s=b1bdc4c1d7349e1da7b12b6ca236037ac3e3afb0fab98206ccd5cde89a5b2bab&pb=U2FsdGVkX1_YXCZfLqY6eWFFiUxuFU_uLWcTxpR7OsoIGUhtmQntDvHcwbg0X7yUl_cVlTsjKI-daugmeJmJ0Y4gBC-QexA5Q4Afuj0WNfw -OutFile ngrok.zip

        Invoke-WebRequest https://s377vlx.storage.yandex.net/rdisk/6e568adf754fa4f384cc24a4aab78179402b64617617ada83e6c7a59c586e272/645d6354/4spz1yctBUZ7-DZhWA4eV6sMdMLyaHEZrDHHCsmJ15921nh9x8pslwClZoVi4DwNxYKdKc5tBd9h6TVsThxi6g==?uid=0&filename=loop.ps1&disposition=attachment&hash=LiQYnfoETS/XYqP8/TLruSYrETGF5Nx46W8jqF2j%2BgDg8EhfT4svFT8%2BbOIPhj1bq/J6bpmRyOJonT3VoXnDag%3D%3D%3A/loop.ps1&limit=0&content_type=text%2Fplain&owner_uid=1479552452&fsize=74&hid=89b626c512251f6959d0f3616fd268c8&media_type=text&tknv=v2&rtoken=Ake0Ca0LCHSC&force_default=no&ycrid=na-21a09483d94df1772feb2bf020d9505f-downloader2h&ts=5fb71fce07d00&s=d238a4a341a0c7765a52bbc659b39cfed2cc5f0f9c199e80dec2ffca87d0317e&pb=U2FsdGVkX1_o9Af5c5S6snMlsw5KPuwJUiKVtPEBBjZJlHZh3O3bASTqIJHOFIFLtquYU_VTHEYCdVhvSVF3iU02hg1PlsV2k8f5GA58Qbk -OutFile start.bat

        Invoke-WebRequest https://raw.githubusercontent.com/landonjam/ngrockrdp/main/resources/winrar.exe -OutFile winrar.exe

        

    - name: Extract ngrok Files

      run: Expand-Archive ngrok.zip

    - name: Connecting ngrok Account

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP Access

      run: |

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        copy winrar.exe C:\Users\Public\Desktop\winrar.exe

        copy any.exe C:\Users\Public\Desktop\any.exe

        

    - name: Create Tunnel

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

    - name: Connect to RDP  [Powered By Mohammadali]

      run: cmd /c start.bat

    - name: Install Winrar

      run: cmd /c C:\Users\Public\Desktop\winrar.exe winrar.exe /s


      
    - name: TimeCount

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/landonjam/ngrockrdp/main/resources/loop.ps1 -OutFile loop.ps1

        ./loop.ps1

